services:
  - type: web
    name: pdfforge
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
