"""Add user roles, plans, Stripe, conversion tracking

Revision ID: 358fa32683f7
Revises: 0c767141244c
Create Date: 2025-06-29 17:33:29.559219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358fa32683f7'
down_revision = '0c767141244c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('conversion_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_conversion_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_conversion_date')
        batch_op.drop_column('conversion_count')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('plan_name')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('status')
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###
