"""User auth, plan, Stripe, conversion tracking

Revision ID: 4ff8e817dcf5
Revises: 358fa32683f7
Create Date: 2025-06-29 17:42:47.355364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff8e817dcf5'
down_revision = '358fa32683f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_used', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('stripe_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('plan_name')
        batch_op.drop_column('last_conversion_date')
        batch_op.drop_column('is_pro')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_pro', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('last_conversion_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('stripe_id')
        batch_op.drop_column('last_used')
        batch_op.drop_column('plan')

    op.drop_table('subscription')
    # ### end Alembic commands ###
