"""Add referral and pro expiry fields to user

Revision ID: 93b83b6f36d7
Revises: 9b10406a1d8e
Create Date: 2025-06-30 00:36:34.515776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b83b6f36d7'
down_revision = '9b10406a1d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('status')
        batch_op.drop_column('stripe_session_id')
        batch_op.drop_column('plan_name')
        batch_op.drop_column('stripe_payment_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('stripe_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referral_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pro_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_referral_code', ['referral_code'])
        batch_op.drop_column('stripe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pro_expiry')
        batch_op.drop_column('referral_credits')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sa.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_id', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('stripe_session_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('billing_cycle', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
